name: publish

on:
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/check.yml
    secrets: inherit

  publish:
    runs-on: windows-2022
    needs: test

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Build
        run: |
          choco pack
          choco install bottom -dv -s .
          btm -V

      - name: Publish
        run: |
          choco apikey --key ${{ secrets.CHOCO_API_KEY }} --source https://push.chocolatey.org/
          choco push -s https://push.chocolatey.org/
